server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://47.98.136.216/wallet?useSSL=false
    username: root
    password: wj@110120
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
mybatis:
  type-aliases-package: cn.itcast.userservice.pojo




