server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://47.98.136.216/wallet?useSSL=false
    username: root
    password: wj@110120
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
mybatis:
  type-aliases-package: cn.itcast.userservice.pojo
eureka:         #配置eureka客户端
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka




